import 'package:flutter/material.dart';

const Color kColorsShade = Color(0xFFBDBDBD);
const Color kTextColor = Color(0xFF616161);

//NAVIGASI NAME
String LOGIN_SCREEN = 'LOGIN_SCREEN';
String REGISTER_SCREEN = 'REGISTER_SCREEN';
String HOME_SCREEN = 'HOME_SCREEN';
String PEMBAYARAN_SCREEN = 'PEMBAYARAN_SCREEN';
String DETAIL_SCREEN = 'DETAIL_SCREEN';
String PROFILE_SCREEN = 'PROFILE_SCREEN';
String PESANAN_SCREEN = 'PESANAN_SCREEN';
String SETTING_SCREEN = 'SETTING_SCREEN';
String FINISH_SCREEN = 'FINISH_SCREEN';
